# Generated by Django 2.2.4 on 2019-08-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='name',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
